#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(pkg1 pkg2 pkg3)
timestamp=2021-08-01T10:27Z
maintainer="None <none@example.org>"
installdepends=(dep)
pkgver=5:4.3.2-1
license=MIT

image=base:v2.1
_upver="${pkgver%-*}"
_upver="${_upver#*:}"
source=("https://example.org/toltec/pkg/release-$_upver.zip")
sha256sums=(SKIP)

prepare() {
    echo "Prepare function"
}

build() {
    echo "Build function"
}

pkg1() {
    pkgdesc="First package"
    url="https://example.org/toltec/pkg/$pkgname"
    section="first"

    package() {
        echo "First package function"
    }
}

pkg2() {
    pkgdesc="Second package"
    url="https://example.org/toltec/pkg/$pkgname"
    section="second"

    package() {
        echo "Second package function"
    }
}

pkg3() {
    pkgdesc="Third package"
    url="https://example.org/toltec/pkg/$pkgname"
    section="third"
    license=GPL-3.0
    installdepends+=(other-dep)

    package() {
        echo "Third package function"
    }
}
