#!/usr/bin/env bash
# Copyright (c) 2023 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rm1 rm2 rmall)
pkgnames=(foo bar)
url=https://toltec-dev.org/
pkgver=0.0.0-1
timestamp=2023-12-23T20:46:51Z
section="utils"
maintainer="Eeems <eeems@eeems.email>"
license=MIT
image=base:v3.1
source=()
sha256sums=()

build() {
    true
}

foo() {
    pkgdesc="Foo"
    package() {
        true
    }
}
bar() {
    pkgdesc="Bar"
    package() {
        true
    }
}

